'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  lang: Language;
  isRTL: boolean;
  setLang: (lang: Language) => void;
  t: typeof translations.en;
}

const translations = {
  ar: {
    appName: 'Table Zone',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب؟',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    tables: 'الطاولات',
    settings: 'الإعدادات',
    members: 'الفريق',
    subscription: 'الاشتراك',
    menuDesign: 'تصميم القائمة',
    profile: 'الملف الشخصي',
    workspace: 'مساحة العمل',
    startTimer: 'بدء المؤقت',
    stopTimer: 'إيقاف المؤقت',
    free: 'متاح',
    occupied: 'مشغول',
    warning: 'تحذير',
    alert: 'تنبيه',
    note: 'ملاحظة',
    addNote: 'إضافة ملاحظة',
    inviteMember: 'دعوة عضو',
    pending: 'قيد الانتظار',
    active: 'نشط',
    lapsed: 'منتهي',
    subscriptionRequired: 'الاشتراك مطلوب',
    subscriptionRequiredDesc: 'يجب الاشتراك لاستخدام المؤقت',
    viewPlans: 'عرض الخطط',
    bankTransfer: 'تحويل بنكي',
    uploadReceipt: 'رفع الإيصال',
    receiptUploaded: 'تم رفع الإيصال',
    thanksForPurchase: 'شكراً لشرائك',
    subscriptionPending: 'سيتم تفعيل اشتراكك قريباً',
    plan: 'الخطة',
    price: 'السعر',
    duration: 'المدة',
    monthly: 'شهري',
    quarterly: '3 أشهر',
    staffSeats: 'مقاعد الموظفين',
    extraSeatPrice: 'سعر المقعد الإضافي',
    requestSubscription: 'طلب الاشتراك',
    requestExtraSeats: 'طلب مقاعد إضافية',
    workspaceFull: 'مساحة العمل ممتلئة',
    workspaceFullDesc: 'جميع المقاعد مشغولة حالياً',
    owner: 'المالك',
    staff: 'موظف',
    remove: 'إزالة',
    leave: 'مغادرة',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    reject: 'رفض',
    save: 'حفظ',
    delete: 'حذف',
    deleteTableConfirm: 'هل أنت متأكد من حذف هذه الطاولة؟',
    addTable: 'إضافة طاولة',
    tableName: 'اسم الطاولة',
    timerDuration: 'مدة المؤقت (دقيقة)',
    edit: 'تعديل',
    close: 'إغلاق',
    search: 'بحث',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    success: 'تم بنجاح',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'English',
    timezone: 'التوقيت الزمني',
    tableCount: 'عدد الطاولات',
    redAlertMinutes: 'وقت التنبيه (دقيقة)',
    slug: 'الرابط المختصر',
    workspaceName: 'اسم المساحة',
    createWorkspace: 'إنشاء مساحة عمل',
    createWorkspaceDesc: 'أنشئ مساحة عمل مقهاك لبدء إدارة طاولاتك',
    createWorkspaceButton: 'إنشاء المساحة',
    workspaceCreated: 'تم إنشاء مساحة العمل بنجاح',
    noWorkspace: 'ليس لديك مساحة عمل',
    noWorkspaceDesc: 'أنشئ مساحة عملك الآن لتبدأ',
    onboardingTitle: 'مرحباً بك في Table Zone',
    onboardingDesc: 'لنبدأ بإعداد مساحة عملك',
    next: 'التالي',
    back: 'السابق',
    finish: 'إنهاء',
    step: 'خطوة',
    of: 'من',
    timerRunning: 'المؤقت يعمل',
    timerStopped: 'المؤقت متوقف',
    overtime: 'تجاوز الوقت',
    minutesRemaining: 'دقيقة متبقية',
    sendInvite: 'إرسال دعوة',
    invitationSent: 'تم إرسال الدعوة',
    acceptInvite: 'قبول الدعوة',
    joinWorkspace: 'الانضمام إلى',
    expiredInvite: 'انتهت صلاحية الدعوة',
    teamInvitation: 'دعوة فريق',
    invitedToJoin: 'تمت دعوتك للانضمام إلى',
    invitedBy: 'مدعو من قبل',
    welcome: 'مرحباً!',
    joinedWorkspace: 'لقد انضممت إلى',
    redirecting: 'جاري التوجيه...',
    invitationError: 'خطأ في الدعوة',
    invalidOrExpiredInvitation: 'دعوة غير صالحة أو منتهية الصلاحية',
    failedToAcceptInvitation: 'فشل قبول الدعوة',
    goToLogin: 'الذهاب إلى تسجيل الدخول',
    resend: 'إعادة إرسال',
    cancelInvite: 'إلغاء الدعوة',
    inviteCreated: 'تم إنشاء الدعوة',
    shareInvite: 'مشاركة الدعوة',
    copyLink: 'نسخ الرابط',
    linkCopied: 'تم نسخ الرابط',
    shareViaWhatsApp: 'مشاركة عبر واتساب',
    inviteLink: 'رابط الدعوة',
    sendTo: 'إرسال إلى',
    timeLeft: 'متبقي',
    ready: 'جاهز',
    start: 'بدء',
    stop: 'إيقاف',
    transfer: 'تبديل',
    transferTo: 'نقل إلى',
    noFreeTables: 'لا توجد طاولات فارغة',
    status: {
      free: 'متاح',
      occupied: 'مشغول',
      warning: 'تحذير',
      alert: 'تنبيه',
    },
    landing: {
      navPricing: 'الأسعار',
      navPartners: 'شركاؤنا',
      getStarted: 'ابدأ الآن',
      startFree: 'ابدأ مجاناً',
      eyebrowHero: 'منصة إدارة المطاعم',
      heroTitle: 'منتجان لمطعمك،',
      heroTitleHighlight: 'تحت مظلة واحدة',
      heroDesc: 'مؤقتات حية لإدارة جلسات طاولاتك، وقائمة QR تتيح لزبائنك تصفح منيوك من جوالهم — بدون تطبيق.',
      timerCardTitle: 'مؤقتات الطاولات',
      timerCardSubtitle: 'لوحة المشغّل',
      timerCardAlert: 'تنبيه جديد',
      timerCardHint: 'اسحب وأفلت الجلسات بين الطاولات',
      qrCardNew: 'جديد',
      qrCardTitle: 'قائمة QR',
      qrCardSubtitle: 'منيو رقمي للزبائن',
      qrCardBadge: 'بدون تطبيق',
      scanLine1: 'امسح',
      scanLine2: 'للقائمة',
      scanForMenu: 'امسح للقائمة',
      mockCafeName: 'الفنار كافيه',
      mockTableLabel: '📍 طاولة ٠٤',
      mockTable04: 'طاولة ٠٤',
      mockTabStarters: 'مقبلات',
      mockTabMains: 'رئيسية',
      mockTabDrinks: 'مشروبات',
      mockTable1: 'طاولة ١',
      mockTable2: 'طاولة ٢',
      mockTable3: 'طاولة ٣',
      mockTable4: 'طاولة ٤',
      statusFree: 'فارغة',
      statusOccupied: 'مشغولة',
      statusWarning: 'تحذير',
      statusAlert: 'تجاوز',
      ourPartners: 'شركاؤنا',
      eyebrowQR: 'المنتج الثاني · قائمة QR',
      qrSectionTitle: 'منيو رقمي لزبائنك، بدون تطبيق',
      qrSectionDesc: 'ضع رمز QR على كل طاولة — يمسحه الزبون ويتصفح قائمتك كاملة من جواله. الأسعار والأصناف تتحدث فوراً من لوحتك.',
      qrStep1Title: 'ولّد كود QR لكل طاولة',
      qrStep1Desc: 'نولّد أكواداً فريدة لطاولاتك — اطبعها أو ضعها في حامل.',
      qrStep2Title: 'الزبون يمسح ويتصفح',
      qrStep2Desc: 'تفتح القائمة مباشرة في المتصفح، بدون تطبيق أو تسجيل.',
      qrStep3Title: 'قائمة دائماً محدّثة',
      qrStep3Desc: 'تعديل الأسعار والأصناف يظهر فوراً لجميع الطاولات.',
      eyebrowPricing: 'الأسعار',
      pricingTitle: 'ابدأ مجاناً، ادفع وقت ما تكبر',
      pricingDesc: 'أسعار شفافة بالريال السعودي، بدون عقود.',
      loadingPlans: 'جاري تحميل الخطط...',
      failedToLoad: 'تعذر تحميل الخطط',
      tryAgain: 'حاول مجدداً',
      planMonthly: 'شهري',
      sarPerMonth: 'ر.س / شهر',
      planQuarterly: 'ربع سنوي',
      sarPerQuarter: 'ر.س / ربع سنة',
      mostPopular: 'الأكثر شعبية',
      noPlans: 'لا توجد خطط متاحة حالياً',
      featUnlimitedTimers: 'مؤقتات غير محدودة',
      featQRMenu: 'قائمة QR',
      featSupport: 'دعم فني',
      featAdvancedQR: 'قائمة QR متقدمة',
      featPrioritySupport: 'دعم ٢٤/٧ بأولوية',
      featSaveMore: 'توفير أكثر',
      ctaTitle: 'جاهز تشغّل مطعمك بشكل أذكى؟',
      ctaDesc: 'سجّل في دقيقة، ابدأ بمؤقتات الطاولات، وفعّل قائمة QR في نفس اليوم.',
      talkToSales: 'تحدث مع المبيعات',
      footerDesc: 'منصة سعودية لإدارة طاولات المطاعم والمقاهي — مؤقتات حية وقائمة QR في مكان واحد.',
      footerColProduct: 'المنتج',
      footerTimers: 'المؤقتات',
      footerColCompany: 'الشركة',
      footerAbout: 'عنّا',
      footerContact: 'تواصل معنا',
      footerColSupport: 'الدعم',
      footerHelp: 'مركز المساعدة',
      footerTerms: 'شروط الخدمة',
      footerPrivacy: 'سياسة الخصوصية',
      footerEula: 'اتفاقية الترخيص',
      footerCopyright: '© ٢٠٢٦ Table Zone · جميع الحقوق محفوظة',
      footerMadeIn: 'صنع بـ ♥ في الرياض',
    },
  },
  en: {
    appName: 'Table Zone',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    logout: 'Logout',
    dashboard: 'Dashboard',
    tables: 'Tables',
    settings: 'Settings',
    members: 'Team',
    subscription: 'Subscription',
    menuDesign: 'Menu Design',
    profile: 'Profile',
    workspace: 'Workspace',
    startTimer: 'Start Timer',
    stopTimer: 'Stop Timer',
    free: 'Free',
    occupied: 'Occupied',
    warning: 'Warning',
    alert: 'Alert',
    note: 'Note',
    addNote: 'Add Note',
    inviteMember: 'Invite Member',
    pending: 'Pending',
    active: 'Active',
    lapsed: 'Lapsed',
    subscriptionRequired: 'Subscription Required',
    subscriptionRequiredDesc: 'You need a subscription to use the timer',
    viewPlans: 'View Plans',
    bankTransfer: 'Bank Transfer',
    uploadReceipt: 'Upload Receipt',
    receiptUploaded: 'Receipt Uploaded',
    thanksForPurchase: 'Thank You for Your Purchase',
    subscriptionPending: 'Your subscription will be activated shortly',
    plan: 'Plan',
    price: 'Price',
    duration: 'Duration',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    staffSeats: 'Staff Seats',
    extraSeatPrice: 'Extra Seat Price',
    requestSubscription: 'Request Subscription',
    requestExtraSeats: 'Request Extra Seats',
    workspaceFull: 'Workspace Full',
    workspaceFullDesc: 'All seats are currently in use',
    owner: 'Owner',
    staff: 'Staff',
    remove: 'Remove',
    leave: 'Leave',
    cancel: 'Cancel',
    confirm: 'Confirm',
    reject: 'Reject',
    save: 'Save',
    delete: 'Delete',
    deleteTableConfirm: 'Are you sure you want to delete this table?',
    addTable: 'Add Table',
    tableName: 'Table Name',
    timerDuration: 'Timer Duration (min)',
    edit: 'Edit',
    close: 'Close',
    search: 'Search',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    language: 'Language',
    arabic: 'العربية',
    english: 'English',
    timezone: 'Timezone',
    tableCount: 'Table Count',
    redAlertMinutes: 'Alert Time (minutes)',
    slug: 'Workspace URL',
    workspaceName: 'Workspace Name',
    createWorkspace: 'Create Workspace',
    createWorkspaceDesc: 'Create your coffee shop workspace to start managing tables',
    createWorkspaceButton: 'Create Workspace',
    workspaceCreated: 'Workspace created successfully',
    noWorkspace: 'No workspace found',
    noWorkspaceDesc: 'Create your workspace now to get started',
    onboardingTitle: 'Welcome to Table Zone',
    onboardingDesc: "Let's set up your workspace",
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    step: 'Step',
    of: 'of',
    timerRunning: 'Timer Running',
    timerStopped: 'Timer Stopped',
    overtime: 'Overtime',
    minutesRemaining: 'minutes remaining',
    sendInvite: 'Send Invite',
    invitationSent: 'Invitation Sent',
    acceptInvite: 'Accept Invitation',
    joinWorkspace: 'Join',
    expiredInvite: 'Invitation Expired',
    teamInvitation: 'Team Invitation',
    invitedToJoin: 'You have been invited to join',
    invitedBy: 'Invited by',
    welcome: 'Welcome!',
    joinedWorkspace: 'You have joined',
    redirecting: 'Redirecting...',
    invitationError: 'Invitation Error',
    invalidOrExpiredInvitation: 'Invalid or expired invitation',
    failedToAcceptInvitation: 'Failed to accept invitation',
    goToLogin: 'Go to Login',
    resend: 'Resend',
    cancelInvite: 'Cancel Invite',
    inviteCreated: 'Invite Created',
    shareInvite: 'Share Invite',
    copyLink: 'Copy Link',
    linkCopied: 'Link Copied',
    shareViaWhatsApp: 'Share via WhatsApp',
    inviteLink: 'Invite Link',
    sendTo: 'Send to',
    timeLeft: 'remaining',
    ready: 'Ready',
    start: 'Start',
    stop: 'Stop',
    transfer: 'Transfer',
    transferTo: 'Transfer to',
    noFreeTables: 'No free tables',
    status: {
      free: 'Free',
      occupied: 'Occupied',
      warning: 'Warning',
      alert: 'Alert',
    },
    landing: {
      navPricing: 'Pricing',
      navPartners: 'Partners',
      getStarted: 'Get Started',
      startFree: 'Start Free',
      eyebrowHero: 'Restaurant Management Platform',
      heroTitle: 'Two products for your restaurant,',
      heroTitleHighlight: 'under one roof',
      heroDesc: 'Live timers to manage your table sessions, and a QR menu that lets your customers browse your menu from their phones — no app needed.',
      timerCardTitle: 'Table Timers',
      timerCardSubtitle: 'Operator Dashboard',
      timerCardAlert: 'New Alert',
      timerCardHint: 'Drag and drop sessions between tables',
      qrCardNew: 'New',
      qrCardTitle: 'QR Menu',
      qrCardSubtitle: 'Digital menu for customers',
      qrCardBadge: 'No app needed',
      scanLine1: 'Scan',
      scanLine2: 'menu',
      scanForMenu: 'Scan for menu',
      mockCafeName: 'Al Fanar Cafe',
      mockTableLabel: '📍 Table 04',
      mockTable04: 'Table 04',
      mockTabStarters: 'Starters',
      mockTabMains: 'Mains',
      mockTabDrinks: 'Drinks',
      mockTable1: 'Table 1',
      mockTable2: 'Table 2',
      mockTable3: 'Table 3',
      mockTable4: 'Table 4',
      statusFree: 'Free',
      statusOccupied: 'Occupied',
      statusWarning: 'Warning',
      statusAlert: 'Overtime',
      ourPartners: 'Our Partners',
      eyebrowQR: 'Product 2 · QR Menu',
      qrSectionTitle: 'Digital menu for your customers, no app needed',
      qrSectionDesc: 'Place a QR code on each table — customers scan it and browse your full menu from their phone. Prices and items update instantly from your dashboard.',
      qrStep1Title: 'Generate a QR code for each table',
      qrStep1Desc: 'We generate unique codes for your tables — print them or place them in a stand.',
      qrStep2Title: 'Customer scans and browses',
      qrStep2Desc: 'The menu opens directly in the browser, no app or sign-up needed.',
      qrStep3Title: 'Menu always up to date',
      qrStep3Desc: 'Price and item changes appear instantly across all tables.',
      eyebrowPricing: 'Pricing',
      pricingTitle: 'Start Free, Pay as You Grow',
      pricingDesc: 'Transparent pricing in SAR, no contracts.',
      loadingPlans: 'Loading plans...',
      failedToLoad: 'Failed to load plans',
      tryAgain: 'Try again',
      planMonthly: 'Monthly',
      sarPerMonth: 'SAR / month',
      planQuarterly: 'Quarterly',
      sarPerQuarter: 'SAR / quarter',
      mostPopular: 'Most Popular',
      noPlans: 'No plans available at the moment',
      featUnlimitedTimers: 'Unlimited timers',
      featQRMenu: 'QR Menu',
      featSupport: 'Support',
      featAdvancedQR: 'Advanced QR Menu',
      featPrioritySupport: '24/7 Priority support',
      featSaveMore: 'Save more',
      ctaTitle: 'Ready to run your restaurant smarter?',
      ctaDesc: 'Register in a minute, start with table timers, and activate your QR menu the same day.',
      talkToSales: 'Talk to Sales',
      footerDesc: 'A Saudi platform for restaurant and café table management — live timers and QR menu in one place.',
      footerColProduct: 'Product',
      footerTimers: 'Timers',
      footerColCompany: 'Company',
      footerAbout: 'About',
      footerContact: 'Contact Us',
      footerColSupport: 'Support',
      footerHelp: 'Help Center',
      footerTerms: 'Terms of Service',
      footerPrivacy: 'Privacy Policy',
      footerEula: 'License Agreement',
      footerCopyright: '© 2026 Table Zone · All rights reserved',
      footerMadeIn: 'Made with ♥ in Riyadh',
    },
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('ar');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'ar' || saved === 'en')) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('language', newLang);
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = newLang;
  };

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const value = {
    lang,
    isRTL: lang === 'ar',
    setLang,
    t: translations[lang],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
