'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  lang: Language;
  isRTL: boolean;
  setLang: (lang: Language) => void;
  t: typeof translations.en;
}

const translations = {
  ar: {
    appName: 'Table Zone',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب؟',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    tablesTimer: 'مؤقت الطاولات',
    tables: 'الطاولات',
    settings: 'الإعدادات',
    members: 'الفريق',
    subscription: 'الاشتراك',
    menuDesign: 'منيو QR',
    profile: 'الملف الشخصي',
    workspace: 'مساحة العمل',
    startTimer: 'بدء المؤقت',
    stopTimer: 'إيقاف المؤقت',
    free: 'متاح',
    occupied: 'مشغول',
    warning: 'تحذير',
    alert: 'تنبيه',
    note: 'ملاحظة',
    addNote: 'إضافة ملاحظة',
    inviteMember: 'دعوة عضو',
    pending: 'قيد الانتظار',
    active: 'نشط',
    lapsed: 'منتهي',
    subscriptionRequired: 'الاشتراك مطلوب',
    subscriptionRequiredDesc: 'يجب الاشتراك لاستخدام المؤقت',
    viewPlans: 'عرض الخطط',
    bankTransfer: 'تحويل بنكي',
    uploadReceipt: 'رفع الإيصال',
    receiptUploaded: 'تم رفع الإيصال',
    thanksForPurchase: 'شكراً لشرائك',
    subscriptionPending: 'سيتم تفعيل اشتراكك قريباً',
    plan: 'الخطة',
    price: 'السعر',
    duration: 'المدة',
    monthly: 'شهري',
    quarterly: '3 أشهر',
    staffSeats: 'مقاعد الموظفين',
    extraSeatPrice: 'سعر المقعد الإضافي',
    requestSubscription: 'طلب الاشتراك',
    requestExtraSeats: 'طلب مقاعد إضافية',
    workspaceFull: 'مساحة العمل ممتلئة',
    workspaceFullDesc: 'جميع المقاعد مشغولة حالياً',
    owner: 'المالك',
    staff: 'موظف',
    remove: 'إزالة',
    leave: 'مغادرة',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    reject: 'رفض',
    save: 'حفظ',
    delete: 'حذف',
    deleteTableConfirm: 'هل أنت متأكد من حذف هذه الطاولة؟',
    addTable: 'إضافة طاولة',
    tableName: 'اسم الطاولة',
    timerDuration: 'مدة المؤقت (دقيقة)',
    edit: 'تعديل',
    close: 'إغلاق',
    search: 'بحث',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    success: 'تم بنجاح',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'English',
    timezone: 'التوقيت الزمني',
    tableCount: 'عدد الطاولات',
    redAlertMinutes: 'وقت التنبيه (دقيقة)',
    slug: 'الرابط المختصر',
    workspaceName: 'اسم المساحة',
    createWorkspace: 'إنشاء مساحة عمل',
    createWorkspaceDesc: 'انشئ مساحة العمل',
    createWorkspaceButton: 'إنشاء المساحة',
    workspaceCreated: 'تم إنشاء مساحة العمل بنجاح',
    noWorkspace: 'ليس لديك مساحة عمل',
    noWorkspaceDesc: 'أنشئ مساحة عملك الآن لتبدأ',
    onboardingTitle: 'مرحباً بك في Table Zone',
    onboardingDesc: 'لنبدأ بإعداد مساحة عملك',
    next: 'التالي',
    back: 'السابق',
    finish: 'إنهاء',
    step: 'خطوة',
    of: 'من',
    timerRunning: 'المؤقت يعمل',
    timerStopped: 'المؤقت متوقف',
    overtime: 'تجاوز الوقت',
    minutesRemaining: 'دقيقة متبقية',
    sendInvite: 'إرسال دعوة',
    invitationSent: 'تم إرسال الدعوة',
    acceptInvite: 'قبول الدعوة',
    joinWorkspace: 'الانضمام إلى',
    expiredInvite: 'انتهت صلاحية الدعوة',
    teamInvitation: 'دعوة فريق',
    invitedToJoin: 'تمت دعوتك للانضمام إلى',
    invitedBy: 'مدعو من قبل',
    welcome: 'مرحباً!',
    joinedWorkspace: 'لقد انضممت إلى',
    redirecting: 'جاري التوجيه...',
    invitationError: 'خطأ في الدعوة',
    invalidOrExpiredInvitation: 'دعوة غير صالحة أو منتهية الصلاحية',
    failedToAcceptInvitation: 'فشل قبول الدعوة',
    goToLogin: 'الذهاب إلى تسجيل الدخول',
    resend: 'إعادة إرسال',
    cancelInvite: 'إلغاء الدعوة',
    inviteCreated: 'تم إنشاء الدعوة',
    shareInvite: 'مشاركة الدعوة',
    copyLink: 'نسخ الرابط',
    linkCopied: 'تم نسخ الرابط',
    shareViaWhatsApp: 'مشاركة عبر واتساب',
    inviteLink: 'رابط الدعوة',
    sendTo: 'إرسال إلى',
    timeLeft: 'متبقي',
    ready: 'جاهز',
    start: 'بدء',
    stop: 'إيقاف',
    transfer: 'تبديل',
    transferTo: 'نقل إلى',
    noFreeTables: 'لا توجد طاولات فارغة',
    status: {
      free: 'متاح',
      occupied: 'مشغول',
      warning: 'تحذير',
      alert: 'تنبيه',
    },
    landing: {
      navQrMenu: 'قائمة QR',
      navPricing: 'الأسعار',
      navPartners: 'شركاؤنا',
      getStarted: 'ابدأ الآن',
      startNow: 'ابدأ الآن',
      heroTitle: 'كل مايحتاجه عملائك',
      heroTitleHighlight: 'تحت مظلة واحدة',
      heroDesc: 'مؤقتات الطاولة لإدارة وقت طاولاتك، وقائمة QR تتيح لزبائنك تصفح المنيو من جوالهم.',
      timerCardTitle: 'مؤقتات الطاولات',
      timerCardSubtitle: 'لوحة المشغّل',
      timerCardAlert: 'تنبيه جديد',
      qrCardTitle: 'قائمة QR',
      qrCardSubtitle: 'منيو رقمي للزبائن',
      qrStickerLine1: 'قائمتك قابلة',
      qrStickerLine2: 'للتخصيص بالكامل',
      venueRestaurant: 'مطعم',
      venueCafe: 'كوفي',
      scanLine1: 'امسح',
      scanLine2: 'للقائمة',
      mockTable1: 'طاولة ١',
      mockTable2: 'طاولة ٢',
      mockTable3: 'طاولة ٣',
      mockTable4: 'طاولة ٤',
      statusFree: 'فارغة',
      statusOccupied: 'مشغولة',
      statusWarning: 'تحذير',
      statusAlert: 'تجاوز',
      timersTitle: 'تابع كل طاولة، لحظة بلحظة',
      timersDesc: 'أربع حالات واضحة تحافظ على سير الخدمة بدون ارتباك.',
      timerDescFree: 'الطاولة فارغة وجاهزة لجلسة جديدة',
      timerDescOccupied: 'جلسة نشطة، المؤقت يعدّ تنازلياً',
      timerDescWarning: 'أقل من ٥ دقائق',
      timerDescAlert: 'تجاوز الوقت',
      ourPartners: 'شركاؤنا',
      qrSectionTitle: 'منيو رقمي لزبائنك',
      qrSectionDesc: 'ضع رمز QR على كل طاولة، يمسحه الزبون ويتصفح قائمتك كاملة من جواله. الأسعار والأصناف تتحدث فوراً من لوحتك.',
      qrStep1Title: 'ولّد كود QR لكل طاولة',
      qrStep1Desc: 'نولّد أكواداً فريدة لطاولاتك، اطبعها أو ضعها في حامل.',
      qrStep2Title: 'الزبون يمسح ويتصفح',
      qrStep2Desc: 'تفتح القائمة مباشرة في المتصفح، بدون تطبيق أو تسجيل.',
      qrStep3Title: 'قائمة دائماً محدّثة',
      qrStep3Desc: 'تعديل الأسعار والأصناف يظهر فوراً لجميع الطاولات.',
      pricingTitle: 'ابدأ الآن ونظم عملك',
      loadingPlans: 'جاري تحميل الخطط...',
      failedToLoad: 'تعذر تحميل الخطط',
      tryAgain: 'حاول مجدداً',
      mostPopular: 'الأكثر شيوعاً',
      noPlans: 'لا توجد خطط متاحة حالياً',
      planMenuTitle: 'قائمة QR',
      planTablesTitle: 'الطاولات',
      planComboTitle: 'الطاولات + القائمة',
      sar: 'SAR',
      days: 'يوم',
      featMenuQrDesign: 'قائمة رقمية بتصميم QR',
      featTemplates: '4 قوالب تصميم جاهزة',
      featCustomize: 'تخصيص الألوان والشعار',
      featManageProducts: 'إدارة المنتجات والتصنيفات',
      featOneSeat: 'مقعد موظف واحد',
      featSupport: 'دعم فني',
      featSmartTimers: 'مؤقتات ذكية للطاولات',
      featTrackStatus: 'تتبع حالة الطاولات',
      featUsageAlerts: 'تنبيهات وقت الاستخدام',
      featAllTables: 'كل مميزات خطة الطاولات',
      featAllMenu: 'كل مميزات خطة القائمة',
      featFullIntegration: 'تكامل كامل بين المنتجين',
      footerDesc: 'منصة سعودية لإدارة طاولات المطاعم والمقاهي، مؤقتات للطاولات وقائمة QR في مكان واحد.',
      footerColProduct: 'المنتج',
      footerTimers: 'المؤقتات',
      footerColCompany: 'الشركة',
      footerAbout: 'عنّا',
      footerContact: 'تواصل معنا',
      footerColSupport: 'الدعم',
      footerHelp: 'مركز المساعدة',
      footerTerms: 'شروط الخدمة',
      footerPrivacy: 'سياسة الخصوصية',
      footerEula: 'اتفاقية الترخيص',
      footerCopyright: '© ٢٠٢٦ Table Zone · جميع الحقوق محفوظة',
    },
  },
  en: {
    appName: 'Table Zone',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    logout: 'Logout',
    dashboard: 'Dashboard',
    tablesTimer: 'Tables Timer',
    tables: 'Tables',
    settings: 'Settings',
    members: 'Team',
    subscription: 'Subscription',
    menuDesign: 'QR Menu',
    profile: 'Profile',
    workspace: 'Workspace',
    startTimer: 'Start Timer',
    stopTimer: 'Stop Timer',
    free: 'Free',
    occupied: 'Occupied',
    warning: 'Warning',
    alert: 'Alert',
    note: 'Note',
    addNote: 'Add Note',
    inviteMember: 'Invite Member',
    pending: 'Pending',
    active: 'Active',
    lapsed: 'Lapsed',
    subscriptionRequired: 'Subscription Required',
    subscriptionRequiredDesc: 'You need a subscription to use the timer',
    viewPlans: 'View Plans',
    bankTransfer: 'Bank Transfer',
    uploadReceipt: 'Upload Receipt',
    receiptUploaded: 'Receipt Uploaded',
    thanksForPurchase: 'Thank You for Your Purchase',
    subscriptionPending: 'Your subscription will be activated shortly',
    plan: 'Plan',
    price: 'Price',
    duration: 'Duration',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    staffSeats: 'Staff Seats',
    extraSeatPrice: 'Extra Seat Price',
    requestSubscription: 'Request Subscription',
    requestExtraSeats: 'Request Extra Seats',
    workspaceFull: 'Workspace Full',
    workspaceFullDesc: 'All seats are currently in use',
    owner: 'Owner',
    staff: 'Staff',
    remove: 'Remove',
    leave: 'Leave',
    cancel: 'Cancel',
    confirm: 'Confirm',
    reject: 'Reject',
    save: 'Save',
    delete: 'Delete',
    deleteTableConfirm: 'Are you sure you want to delete this table?',
    addTable: 'Add Table',
    tableName: 'Table Name',
    timerDuration: 'Timer Duration (min)',
    edit: 'Edit',
    close: 'Close',
    search: 'Search',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    language: 'Language',
    arabic: 'العربية',
    english: 'English',
    timezone: 'Timezone',
    tableCount: 'Table Count',
    redAlertMinutes: 'Alert Time (minutes)',
    slug: 'Workspace URL',
    workspaceName: 'Workspace Name',
    createWorkspace: 'Create Workspace',
    createWorkspaceDesc: 'Create your coffee shop workspace to start managing tables',
    createWorkspaceButton: 'Create Workspace',
    workspaceCreated: 'Workspace created successfully',
    noWorkspace: 'No workspace found',
    noWorkspaceDesc: 'Create your workspace now to get started',
    onboardingTitle: 'Welcome to Table Zone',
    onboardingDesc: "Let's set up your workspace",
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    step: 'Step',
    of: 'of',
    timerRunning: 'Timer Running',
    timerStopped: 'Timer Stopped',
    overtime: 'Overtime',
    minutesRemaining: 'minutes remaining',
    sendInvite: 'Send Invite',
    invitationSent: 'Invitation Sent',
    acceptInvite: 'Accept Invitation',
    joinWorkspace: 'Join',
    expiredInvite: 'Invitation Expired',
    teamInvitation: 'Team Invitation',
    invitedToJoin: 'You have been invited to join',
    invitedBy: 'Invited by',
    welcome: 'Welcome!',
    joinedWorkspace: 'You have joined',
    redirecting: 'Redirecting...',
    invitationError: 'Invitation Error',
    invalidOrExpiredInvitation: 'Invalid or expired invitation',
    failedToAcceptInvitation: 'Failed to accept invitation',
    goToLogin: 'Go to Login',
    resend: 'Resend',
    cancelInvite: 'Cancel Invite',
    inviteCreated: 'Invite Created',
    shareInvite: 'Share Invite',
    copyLink: 'Copy Link',
    linkCopied: 'Link Copied',
    shareViaWhatsApp: 'Share via WhatsApp',
    inviteLink: 'Invite Link',
    sendTo: 'Send to',
    timeLeft: 'remaining',
    ready: 'Ready',
    start: 'Start',
    stop: 'Stop',
    transfer: 'Transfer',
    transferTo: 'Transfer to',
    noFreeTables: 'No free tables',
    status: {
      free: 'Free',
      occupied: 'Occupied',
      warning: 'Warning',
      alert: 'Alert',
    },
    landing: {
      navQrMenu: 'QR Menu',
      navPricing: 'Pricing',
      navPartners: 'Partners',
      getStarted: 'Get Started',
      startNow: 'Start Now',
      heroTitle: 'Everything your customers need',
      heroTitleHighlight: 'under one roof',
      heroDesc: 'Table timers to manage your tables\' time, and a QR menu that lets your customers browse the menu from their phones.',
      timerCardTitle: 'Table Timers',
      timerCardSubtitle: 'Operator Dashboard',
      timerCardAlert: 'New Alert',
      qrCardTitle: 'QR Menu',
      qrCardSubtitle: 'Digital menu for customers',
      qrStickerLine1: 'Your menu is',
      qrStickerLine2: 'fully customizable',
      venueRestaurant: 'Restaurant',
      venueCafe: 'Café',
      scanLine1: 'Scan for',
      scanLine2: 'menu',
      mockTable1: 'Table 1',
      mockTable2: 'Table 2',
      mockTable3: 'Table 3',
      mockTable4: 'Table 4',
      statusFree: 'Free',
      statusOccupied: 'Occupied',
      statusWarning: 'Warning',
      statusAlert: 'Overtime',
      timersTitle: 'Track every table, moment by moment',
      timersDesc: 'Four clear statuses keep service flowing without confusion.',
      timerDescFree: 'The table is empty and ready for a new session',
      timerDescOccupied: 'Active session, the timer counts down',
      timerDescWarning: 'Less than 5 minutes left',
      timerDescAlert: 'Time exceeded',
      ourPartners: 'Our Partners',
      qrSectionTitle: 'A digital menu for your customers',
      qrSectionDesc: 'Place a QR code on each table. Customers scan it and browse your full menu from their phone. Prices and items update instantly from your dashboard.',
      qrStep1Title: 'Generate a QR code for each table',
      qrStep1Desc: 'We generate unique codes for your tables. Print them or place them in a stand.',
      qrStep2Title: 'Customers scan and browse',
      qrStep2Desc: 'The menu opens directly in the browser, no app or sign-up needed.',
      qrStep3Title: 'A menu that is always up to date',
      qrStep3Desc: 'Price and item changes appear instantly across all tables.',
      pricingTitle: 'Start now and organize your business',
      loadingPlans: 'Loading plans...',
      failedToLoad: 'Failed to load plans',
      tryAgain: 'Try again',
      mostPopular: 'Most Popular',
      noPlans: 'No plans available at the moment',
      planMenuTitle: 'QR Menu',
      planTablesTitle: 'Table Management',
      planComboTitle: 'Tables + Menu',
      sar: 'SAR',
      days: 'days',
      featMenuQrDesign: 'Digital QR menu',
      featTemplates: '4 ready-made design templates',
      featCustomize: 'Customize colors & logo',
      featManageProducts: 'Manage products & categories',
      featOneSeat: '1 staff seat',
      featSupport: 'Technical support',
      featSmartTimers: 'Smart table timers',
      featTrackStatus: 'Track table status',
      featUsageAlerts: 'Usage time alerts',
      featAllTables: 'All Table Management features',
      featAllMenu: 'All QR Menu features',
      featFullIntegration: 'Full integration between both',
      footerDesc: 'A Saudi platform for restaurant and café table management, table timers and QR menu in one place.',
      footerColProduct: 'Product',
      footerTimers: 'Timers',
      footerColCompany: 'Company',
      footerAbout: 'About',
      footerContact: 'Contact Us',
      footerColSupport: 'Support',
      footerHelp: 'Help Center',
      footerTerms: 'Terms of Service',
      footerPrivacy: 'Privacy Policy',
      footerEula: 'License Agreement',
      footerCopyright: '© 2026 Table Zone · All rights reserved',
    },
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('ar');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'ar' || saved === 'en')) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('language', newLang);
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = newLang;
  };

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const value = {
    lang,
    isRTL: lang === 'ar',
    setLang,
    t: translations[lang],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
